name: Run pytest in moveroplot

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  moveroplot-pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        channels: conda-forge
        channel-priority: flexible
        show-channel-urls: true
    - name: Create env from pinned reqs
      run: |
        conda env create --name dev_env --file requirements/environment.yml
    - name: Install project into env
      run: |
        conda run --name dev_env pip install --no-deps .
    - name: Run pytest
      run: |
        conda run --name dev_env pytest
